#!/bin/bash

swiftly --auth-url="https://identity.api.rackspacecloud.com/v2.0" --auth-user=$WERCKER_RACKSPACE_CLOUDFILES_SWIFTLY_USER --auth-key=$WERCKER_RACKSPACE_CLOUDFILES_SWIFTLY_KEY --region=$WERCKER_RACKSPACE_CLOUDFILES_SWIFTLY_REGION put -i $WERCKER_RACKSPACE_CLOUDFILES_SWIFTLY_PATH $WERCKER_RACKSPACE_CLOUDFILES_SWIFTLY_CONTAINER

